### ISSUE TITLE
Invalid Version: undefined

### ISSUE THREAD

**Issue by JamieBallingall** [purescript-halogen/purescript-halogen-template#27]
Following the instructions in the README leads to the error ```Invalid Version: undefined``` when running either `npm run serve` or `npm run build-prod`.

This appears to be a result of a change to Babel [causing problems](https://github.com/parcel-bundler/parcel/issues/5943) with Parcel.

A temporary fix is to pin the Parcel version to 1.12.3 (rather than ^1.12.4) until the Parcel folks sort this out.

**Comment by thomashoneyman** [comment]
Closed in #29 / #28. Thanks!
